function Progress() {
	global.progress[0]	= false;
	global.progress[1]	= false;
	global.progress[2]	= false;
	global.progress[3]	= false;
	global.progress[4]	= false;
	global.progress[5]	= false;
	global.progress[6]	= false;
	global.progress[7]	= false;
	global.progress[8]	= false;
	global.progress[9]	= false;
	global.progress[10] = false;
	global.progress[11] = false;
	global.progress[12] = false;
	global.progress[13] = false;
	global.progress[14] = false;
	global.progress[15] = false;
	global.progress[16] = false;
	global.progress[17] = false;
	global.progress[18] = false;
	global.progress[19] = false;
	global.progress[20] = false;
}
